version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - pip install --upgrade awscli
      - python -m unittest discover tests
reports:
  pytest_reports:
    files:
      - unittest discover tests
    base-directory: arn:aws:codebuild:ap-south-1:481782230560:report-group/UnitTest
    file-format: JUNITXML
artifacts:
  files:
    - '**/*'
